[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "euro_gas_power"
version = "0.1.0-beta"
description = "Python tools to access fundamental European gas and power data."
authors = [
  { name="Alexander Gardner" }
]
readme = "README.md"
license = { text="MIT" }
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
